var copyDir=require('../index.js');

copyDir({
    rootPath: '/Users/chenhao/工程/开发环境/qian360/webapps/',
    filePathList: [
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/about/about_img1.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/about/about_img2.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/about/map-location.jpg',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/about/legal_banner.jpg',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/home_stats/1.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/home_stats/2.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/home_stats/3.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/home_stats/4.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/logo_activity/1.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/logo_activity/2.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/logo_activity/3.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/logo_activity/4.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/bg_grain.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/couplet_left.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/couplet_right.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/new_year/logo.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/invest_step.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/row_img1.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/row_img2.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/security_img1.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/security_img2.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/security_img3.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/security_img4.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/top_banner.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/novice/row_tit.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/image/home_moneybaby.png',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/themes/soonmes_qzw_v2/script/page/index.js',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/about/contact.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/about/index.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/about/legalAdviser.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/about/team.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/index.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/novice.html',
        '/Users/chenhao/工程/开发环境/qian360/webapps/ROOT/WEB-INF/html_qzw_v2/loan/select.html'
    ],
    createPath: './',
    isLog: true
});